title: Kenta Edmonda # your name (or website title) here
logo: "/images/KentaFoto.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Data Enthusiast
  <br>
  <br>Welcome to my data science portfolio. I created several projects related to data science, such as machine learning models to improve my skills in data science.<br>
  <br>
  <a href="https://www.linkedin.com/in/kentaedmonda/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
